theme: jekyll-theme-minimal
show_downloads: false
title: Data Science XXXX
description: <b>School of Data Science<br>University of Virginia</b><br><br><a href="index.html">Course Overview</a><br><a href="course-calendar.html">Course Calendar</a><br><a href="course-policies.html">Course Policies</a><br>
encoding: UTF-8
